name: vinyl
type: service
icon: vinyl
title: Vinyl
scalable: true

options:
- version: '8.0'
  tag: '8.0-5.2.6'
  default: true
  eol: '2026-09-15T00:00:00+00:00'
- version: '6.0'
  tag: '6.0-5.2.6'

endpoints:
- name: http
  ports:
  - name: http
    number: 6081
    protocol: http
    main: true

links:
- name: backend
  title: Backend
  required: true
  env:
  - name: VARNISH_BACKEND_HOST
    value: '{{link.host}}'
  - name: VARNISH_BACKEND_PORT
    value: '{{link.port}}'
  selectors:
  - type: service
    labels:
    - nginx
  - type: service
    labels:
    - httpd

env:
- name: VARNISH_SECRET
  value: '{{secret}}'
  secret: true
- name: VARNISH_PURGE_KEY
  value: '{{purge_key}}'
  secret: true
- name: VARNISH_PURGE_EXTERNAL_REQUEST_HEADER
  value: X-Real-IP

tokens:
- name: secret
  generate:
    regex: '[0-9a-z-]{32}'
- name: purge_key
  generate:
    regex: '[0-9a-z-]{32}'

labels:
- vinyl
- varnish

configs:
- name: main
  title: Main
  filepath: /etc/gotpl/default.vcl.tmpl
  default:
    source: image
    filepath: /etc/gotpl/default.vcl.tmpl

deployment:
  strategy: rolling
  maxUnavailable: 0
  maxSurge: 1
  minReady: 10s
  progressDeadline: 15m
  shutdownGracePeriod: 30s

helm:
  name: wodby
  source: oci://registry-1.docker.io/wodby/vinyl
  chart: oci://registry-1.docker.io/wodby/vinyl
  version: 0.2.0

workloads:
- name: main
  selector:
    matchLabels:
      app.kubernetes.io/instance: '{{helm.release}}'
  kind: deployment
  primary: true
  helm:
    labels: commonLabels
    annotations: commonAnnotations
    volumes: extraVolumes
  containers:
  - name: vinyl
    image: wodby/vinyl
    helm:
      resources: resources
      env: extraEnvVars
      mounts: extraVolumeMounts
